FROM node:20.20.2-bookworm

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    zip \
    unzip \
    git \
    make \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

CMD ["bash"]
