    // temperature: "temperature",
    // topP: "topP",
    // frequencyPenalty: "frequencyPenalty",
    // presencePenalty: "presencePenalty",
    // bestOf: "bestOf",
    // maxTokens: "maxTokens",
