#!/usr/bin/env python3
"""Build machine-readable indexes for modify/new extension modules.

The goal is not perfect static analysis. It is a useful map for humans and AI:
  - which globals/functions a module provides
  - which existing functions it wraps
  - storage/network/API surfaces it touches
  - wrapper chains and risks
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MOD_DIR = ROOT / "modify/new"
ANALYSIS = ROOT / "analysis"

FUNC_RE = re.compile(r"^(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*\(", re.M)
VAR_RE = re.compile(r"^(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=", re.M)
WINDOW_ASSIGN_RE = re.compile(r"window\.([A-Za-z_$][\w$]*)\s*=", re.M)
ASSIGN_FUNC_RE = re.compile(r"^\s*([A-Za-z_$][\w$]*)\s*=\s*(?:async\s+)?function\s*\(", re.M)
ORIGINAL_RE = re.compile(r"(?:const|let|var)\s+([A-Za-z_$][\w$]*Original[A-Za-z_$0-9]*|__aeOriginal[A-Za-z_$0-9]*)\s*=\s*([A-Za-z_$][\w$]*(?:\.[A-Za-z_$][\w$]*)?)")
LOCALSTORAGE_RE = re.compile(r"localStorage\.(?:getItem|setItem|removeItem)\(['\"]([^'\"]+)")
DB_RE = re.compile(r"\bdb\.([A-Za-z_$][\w$]*)\b")
ROOT_RE = re.compile(r"\broot\.([A-Za-z_$][\w$]*)\b")
FETCH_RE = re.compile(r"\b(?:fetch|root\.superFetch)\(\s*([`'\"])(.*?)\1", re.S)
REGISTER_HOOK_RE = re.compile(r"__aeRegisterBeforeBotReplyHook\(\s*['\"]([^'\"]+)")
COMMAND_LITERAL_RE = re.compile(r"['\"](/(?:[A-Za-z0-9_-]+)(?:\s+[A-Za-z0-9_-]+)?)['\"]")

# Known functions that are patched/wrapped by assignment in this codebase.
KNOWN_WRAP_TARGETS = {
    "getBotReply",
    "sendButtonClickHandler",
    "showThread",
    "__aeHandleCommandText",
    "__aeEnsureShortcutButtons",
    "__aeSearchWeb",
    "__aeProcessImageFile",
    "tryImportingDexieFile",
    "__aeShowExtensionsMenu",
    "__aeShowBasePolicyModal",
    "__aeShowFileExplorer",
    "__aeToggleVoiceRecording",
}


def classify_title(name: str) -> str:
    stem = name.removesuffix(".frag")
    return stem.replace("_", " ")


def scan_file(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    provided = sorted(set(FUNC_RE.findall(text) + VAR_RE.findall(text) + ["window." + x for x in WINDOW_ASSIGN_RE.findall(text)]))

    original_pairs = ORIGINAL_RE.findall(text)
    wraps_set = {target for _orig, target in original_pairs if target in KNOWN_WRAP_TARGETS or target.startswith("__ae")}
    wraps_set.update({name for name in ASSIGN_FUNC_RE.findall(text) if name in KNOWN_WRAP_TARGETS})
    wraps = sorted(wraps_set)

    storage = []
    storage += [f"localStorage.{k}" for k in sorted(set(LOCALSTORAGE_RE.findall(text)))]
    storage += [f"db.{k}" for k in sorted(set(DB_RE.findall(text)))]

    root_calls = sorted(set(ROOT_RE.findall(text)))
    hooks = sorted(set(REGISTER_HOOK_RE.findall(text)))
    commands = sorted(set(x for x in COMMAND_LITERAL_RE.findall(text) if len(x) <= 40))

    network = []
    for _q, url in FETCH_RE.findall(text):
        if url.startswith("http"):
            network.append(url[:160])
    network = sorted(set(network))

    consumes = sorted(set(root_calls + [w for w in wraps]))

    return {
        "title": classify_title(path.name),
        "file": str(path.relative_to(ROOT)),
        "lines": text.count("\n") + 1,
        "bytes": path.stat().st_size,
        "provides": provided,
        "wraps": sorted(wraps),
        "hooks_registered": hooks,
        "commands_seen": commands,
        "storage": sorted(set(storage)),
        "root_api_calls": root_calls,
        "network_literals": network,
        "consumes_or_patches": consumes,
    }


def build_wrapper_chains(mods: dict[str, dict]) -> dict[str, list[str]]:
    chains: dict[str, list[str]] = {}
    for name, meta in mods.items():
        for target in meta.get("wraps", []):
            chains.setdefault(target, []).append(name)
    return {k: v for k, v in sorted(chains.items())}


def write_markdown(mods: dict[str, dict], chains: dict[str, list[str]]) -> None:
    out = []
    out.append("# Extension wrapper chains\n")
    out.append("Generated by `tools/build_extension_indexes.py`.\n")
    if not chains:
        out.append("No wrapper chains detected.\n")
    for target, module_names in chains.items():
        out.append(f"## `{target}`\n")
        for i, name in enumerate(module_names, 1):
            out.append(f"{i}. `{name}`")
        out.append("\nRisk notes:\n")
        out.append("- wrapper order is load-order dependent;\n")
        out.append("- each wrapper should call the previous implementation unless intentionally replacing it;\n")
        out.append("- prefer moving this chain to a registry/hook API when possible.\n")
    out.append("\n# Module summary\n")
    for name, meta in mods.items():
        out.append(f"## `{name}`\n")
        out.append(f"- lines: {meta['lines']}\n")
        if meta["commands_seen"]:
            out.append("- commands/literals: " + ", ".join(f"`{c}`" for c in meta["commands_seen"][:30]) + "\n")
        if meta["hooks_registered"]:
            out.append("- hooks: " + ", ".join(f"`{h}`" for h in meta["hooks_registered"]) + "\n")
        if meta["storage"]:
            out.append("- storage: " + ", ".join(f"`{s}`" for s in meta["storage"][:30]) + "\n")
        if meta["root_api_calls"]:
            out.append("- root APIs: " + ", ".join(f"`root.{r}`" for r in meta["root_api_calls"]) + "\n")
    (ANALYSIS / "extension_wrapper_chains.md").write_text("\n".join(out), encoding="utf-8")


def main() -> int:
    mods = {p.name: scan_file(p) for p in sorted(MOD_DIR.glob("*.frag"))}
    chains = build_wrapper_chains(mods)
    payload = {
        "generated_by": "tools/build_extension_indexes.py",
        "module_count": len(mods),
        "modules": mods,
        "wrapper_chains": chains,
    }
    (ANALYSIS / "extension_module_manifest.json").write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    write_markdown(mods, chains)
    print(f"Wrote {ANALYSIS / 'extension_module_manifest.json'}")
    print(f"Wrote {ANALYSIS / 'extension_wrapper_chains.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
